import PDFDocument from 'pdfkit';

export interface PdfTableColumn {
  header: string;
  width: number;
  align?: 'left' | 'right' | 'center';
}

/**
 * Generate a PDF report with a title, summary stats, and a data table.
 * Returns a Buffer.
 */
export async function generatePdfReport(options: {
  title: string;
  subtitle?: string;
  summary?: { label: string; value: string }[];
  columns: PdfTableColumn[];
  rows: string[][];
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ─── Header ──────────────────────────────────────────────────────────────
    doc
      .fillColor('#1a56db')
      .fontSize(20)
      .font('Helvetica-Bold')
      .text(options.title, { align: 'center' });

    if (options.subtitle) {
      doc
        .fillColor('#6b7280')
        .fontSize(10)
        .font('Helvetica')
        .text(options.subtitle, { align: 'center' });
    }

    doc.moveDown(1);

    // ─── Summary box ──────────────────────────────────────────────────────────
    if (options.summary && options.summary.length) {
      options.summary.forEach((item) => {
        doc
          .fillColor('#374151')
          .fontSize(11)
          .font('Helvetica-Bold')
          .text(`${item.label}: `, { continued: true })
          .font('Helvetica')
          .text(item.value);
      });
      doc.moveDown(1);
    }

    // ─── Table header ─────────────────────────────────────────────────────────
    const startX = 50;
    let y = doc.y;
    const rowHeight = 20;

    doc.rect(startX, y, 495, rowHeight).fill('#1a56db');
    doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
    let x = startX;
    options.columns.forEach((col) => {
      doc.text(col.header, x + 4, y + 6, {
        width: col.width - 8,
        align: col.align || 'left',
      });
      x += col.width;
    });
    y += rowHeight;

    // ─── Table rows ───────────────────────────────────────────────────────────
    doc.font('Helvetica').fontSize(8);
    options.rows.forEach((row, idx) => {
      // Stop if we'd overflow the page
      if (y > 780) {
        doc.addPage();
        y = 50;
      }

      if (idx % 2 === 1) {
        doc.rect(startX, y, 495, rowHeight).fill('#f3f4f6');
      }

      doc.fillColor('#1f2937');
      x = startX;
      options.columns.forEach((col, colIdx) => {
        doc.text(row[colIdx] || '', x + 4, y + 6, {
          width: col.width - 8,
          align: col.align || 'left',
        });
        x += col.width;
      });
      y += rowHeight;
    });

    // ─── Footer ───────────────────────────────────────────────────────────────
    doc
      .moveTo(50, y + 10)
      .fillColor('#9ca3af')
      .fontSize(8)
      .font('Helvetica-Oblique')
      .text(
        `Generated by NINS Hospital Management System — ${new Date().toLocaleString()}`,
        { align: 'center' },
      );

    doc.end();
  });
}
